name: platform-api
recipe: symfony
config:
  webroot: ./public
  php: '8.1'
  cache: redis
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
