controllers:
    resource: ../src/Controller/
    type: attribute
    prefix:
        default: /
        localized: /{_locale}
    requirements:
        _locale: de|en
    defaults: { _locale: de }
#    prefix:
#        default: '/de'
#        af: '/af'
#        am: '/am'
#        ar: '/ar'
#        arn: '/arn'
#        as: '/as'
#        az: '/az'
#        ba: '/ba'
#        be: '/be'
#        bg: '/bg'
#        bn: '/bn'
#        bo: '/bo'
#        br: '/br'
#        bs: '/bs'
#        ca: '/ca'
#        co: '/co'
#        cs: '/cs'
#        cy: '/cy'
#        da: '/da'
#        de: '/de'
#        dsb: '/dsb'
#        dv: '/dv'
#        el: '/el'
#        en: '/en'
#        es: '/es'
#        et: '/et'
#        eu: '/eu'
#        fa: '/fa'
#        fi: '/fi'
#        fil: '/fil'
#        fo: '/fo'
#        fr: '/fr'
#        fy: '/fy'
#        ga: '/ga'
#        gd: '/gd'
#        gl: '/gl'
#        gsw: '/gsw'
#        gu: '/gu'
#        ha: '/ha'
#        he: '/he'
#        hi: '/hi'
#        hr: '/hr'
#        hsb: '/hsb'
#        hu: '/hu'
#        hy: '/hy'
#        id: '/id'
#        ig: '/ig'
#        ii: '/ii'
#        in: '/in'
#        is: '/is'
#        it: '/it'
#        iu: '/iu'
#        iw: '/iw'
#        ja: '/ja'
#        ka: '/ka'
#        kk: '/kk'
#        kl: '/kl'
#        km: '/km'
#        kn: '/kn'
#        kok: '/kok'
#        ko: '/ko'
#        ky: '/ky'
#        lb: '/lb'
#        lo: '/lo'
#        lt: '/lt'
#        lv: '/lv'
#        mi: '/mi'
#        mk: '/mk'
#        ml: '/ml'
#        mn: '/mn'
#        moh: '/moh'
#        mr: '/mr'
#        ms: '/ms'
#        mt: '/mt'
#        nb: '/nb'
#        ne: '/ne'
#        nl: '/nl'
#        nn: '/nn'
#        no: '/no'
#        nso: '/nso'
#        oc: '/oc'
#        or: '/or'
#        pa: '/pa'
#        pl: '/pl'
#        prs: '/prs'
#        ps: '/ps'
#        pt: '/pt'
#        qut: '/qut'
#        quz: '/quz'
#        rm: '/rm'
#        ro: '/ro'
#        ru: '/ru'
#        rw: '/rw'
#        sah: '/sah'
#        sa: '/sa'
#        se: '/se'
#        si: '/si'
#        sk: '/sk'
#        sl: '/sl'
#        sma: '/sma'
#        smj: '/smj'
#        smn: '/smn'
#        sms: '/sms'
#        sq: '/sq'
#        sr: '/sr'
#        sv: '/sv'
#        sw: '/sw'
#        syr: '/syr'
#        ta: '/ta'
#        te: '/te'
#        tg: '/tg'
#        th: '/th'
#        tk: '/tk'
#        tlh: '/tlh'
#        tn: '/tn'
#        tr: '/tr'
#        tt: '/tt'
#        tzm: '/tzm'
#        ug: '/ug'
#        uk: '/uk'
#        ur: '/ur'
#        uz: '/uz'
#        vi: '/vi'
#        wo: '/wo'
#        xh: '/xh'
#        yo: '/yo'
#        zh: '/zh'
authentication_token:
    path: /authentication_token
    methods: ['POST']
